$env.EDITOR = 'nvim'
$env.VISUAL = 'nvim'
$env.LS_COLORS = '$(vivid generate gruvbox-dark-hard)'
$env.WLR_NO_HARDWARE_CURSORS = '1'
$env.NIXOS_OZONE_WL = '1'
$env.MANPAGER = 'nvim +Man!'
$env.TESTING_WORKING = '1'
